behaviors:
  AIRobotGeneric:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 15000000
    time_horizon: 64
    summary_freq: 60000
    threaded: true
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000

environment_parameters:
  max_steps:
    curriculum:
    - name: LessonPushBlock
      completion_criteria: &lessonpushblock_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 3.5
      value: 2500
    - name: LessonPushBlockTwoGoals
      completion_criteria: &lessonpushblock2_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 7
      value: 2500
    - name: LessonPushBlockTwoGoalsWithBall
      completion_criteria: &lessonpushblock2ball_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 9
      value: 2500
    - name: Lesson0
      completion_criteria: &lesson0_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 3.5
        require_reset: true
      value: 2500
    - name: Lesson1
      completion_criteria: &lesson1_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 5
      value: 2300
    - name: Lesson2
      completion_criteria: &lesson2_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 6
      value: 2000
    - name: Lesson3
      completion_criteria: &lesson3_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 7
      value: 2000
    - name: Lesson4
      completion_criteria: &lesson4_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 8
      value: 2000
    - name: Lesson5
      completion_criteria: &lesson5_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 8.5
      value: 2000
    - name: Lesson6
      completion_criteria: &lesson6_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 9
      value: 2000
    - name: Lesson7
      value: 2000

  max_arenas:
    curriculum:
      - name: LessonPushBlock
        completion_criteria: *lessonpushblock_defaults
        value: 64
      - name: LessonPushBlockTwoGoals
        completion_criteria: *lessonpushblock2_defaults
        value: 64
      - name: Lesson0
        value: 16
        completion_criteria: *lesson0_defaults
      - name: Lesson1
        value: 16
        completion_criteria: *lesson1_defaults
      - name: Lesson2
        value: 16
        completion_criteria: *lesson2_defaults
      - name: Lesson3
        value: 16
        completion_criteria: *lesson3_defaults
      - name: Lesson4
        value: 16
        completion_criteria: *lesson4_defaults
      - name: Lesson5
        value: 16
        completion_criteria: *lesson5_defaults
      - name: Lesson6
        value: 16
        completion_criteria: *lesson6_defaults
      - name: Lesson7
        value: 16

  ball_shape:
    curriculum:
      - name: LessonPushBlock
        completion_criteria: *lessonpushblock_defaults
        value: 0
      - name: LessonPushBlockTwoGoals
        completion_criteria: *lessonpushblock2_defaults
        value: 0
      - name: LessonPushBlockTwoGoalsWithBall
        completion_criteria: *lessonpushblock2ball_defaults
        value: 1
      - name: Lesson0
        completion_criteria: *lesson0_defaults
        value: 1
      - name: Lesson1
        completion_criteria: *lesson1_defaults
        value: 1
      - name: Lesson2
        completion_criteria: *lesson2_defaults
        value: 1
      - name: Lesson3
        completion_criteria: *lesson3_defaults
        value: 1
      - name: Lesson4
        completion_criteria: *lesson4_defaults
        value: 1
      - name: Lesson5
        completion_criteria: *lesson5_defaults
        value: 1
      - name: Lesson6
        completion_criteria: *lesson6_defaults
        value: 1
      - name: Lesson7
        value: 1

  level:
    curriculum:
    - name: LessonPushBlock
      completion_criteria: *lessonpushblock_defaults
      value: 4
    - name: LessonPushBlockTwoGoals
      completion_criteria: *lessonpushblock2_defaults
      value: 3
    - name: LessonPushBlockTwoGoals
      completion_criteria: *lessonpushblock2_defaults
      value: 3
    - name: Lesson0
      completion_criteria: *lesson0_defaults
      value: 3
    - name: Lesson1
      completion_criteria: *lesson1_defaults
      value: 3
    - name: Lesson2
      completion_criteria: *lesson2_defaults
      value: 2
    - name: Lesson3
      completion_criteria: *lesson3_defaults
      value: 2
    - name: Lesson4
      completion_criteria: *lesson4_defaults
      value: 2
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 1
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 1
    - name: Lesson7
      value: 1
  spawn_area_margin:
    curriculum:
    - name: LessonPushBlock
      completion_criteria: *lessonpushblock_defaults
      value: 0.5
    - name: LessonPushBlockTwoGoals
      completion_criteria: *lessonpushblock2_defaults
      value: 0.5
    - name: Lesson0
      completion_criteria: *lesson0_defaults
      value: 0.5
    - name: Lesson1
      completion_criteria: *lesson1_defaults
      value: 0.7
    - name: Lesson2
      completion_criteria: *lesson2_defaults
      value: 0.8
    - name: Lesson3
      completion_criteria: *lesson3_defaults
      value: 0.85
    - name: Lesson4
      completion_criteria: *lesson4_defaults
      value: 0.9
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 0.99
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 0.99
    - name: Lesson7
      value: 0.99
  random_obs_dist:
    curriculum:
    - name: Lesson0
      completion_criteria: *lesson0_defaults
      value: 0.0
    - name: Lesson1
      completion_criteria: *lesson1_defaults
      value: 0.01
    - name: Lesson2
      completion_criteria: *lesson2_defaults
      value: 0.01
    - name: Lesson3
      completion_criteria: *lesson3_defaults
      value: 0.01
    - name: Lesson4
      completion_criteria: *lesson4_defaults
      value: 0.02
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 0.02
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 0.02
    - name: Lesson7
      value: 0.02
  random_obs_angle:
    curriculum:
    - name: Lesson0
      completion_criteria: *lesson0_defaults
      value: 0
    - name: Lesson1
      completion_criteria: *lesson1_defaults
      value: 1
    - name: Lesson2
      completion_criteria: *lesson2_defaults
      value: 2
    - name: Lesson3
      completion_criteria: *lesson3_defaults
      value: 2
    - name: Lesson4
      completion_criteria: *lesson4_defaults
      value: 2
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      value: 2
  number_of_blue_agents:
    curriculum:
    - name: Lesson0
      completion_criteria: *lesson0_defaults
      value: 1
    - name: Lesson1
      completion_criteria: *lesson1_defaults
      value: 1
    - name: Lesson2
      completion_criteria: *lesson2_defaults
      value: 2
    - name: Lesson3
      completion_criteria: *lesson3_defaults
      value: 2
    - name: Lesson4
      completion_criteria: *lesson4_defaults
      value: 2
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      value: 2
  number_of_red_agents:
    curriculum:
    - name: LessonPushBlock
      completion_criteria: *lessonpushblock_defaults
      value: 0
    - name: LessonPushBlockTwoGoals
      completion_criteria: *lessonpushblock2_defaults
      value: 0
    - name: LessonPushBlockTwoGoalsWithBall
      completion_criteria: *lessonpushblock2ball_defaults
      value: 0
    - name: Lesson0
      completion_criteria: *lesson0_defaults
      value: 1
    - name: Lesson1
      completion_criteria: *lesson1_defaults
      value: 1
    - name: Lesson2
      completion_criteria: *lesson2_defaults
      value: 2
    - name: Lesson3
      completion_criteria: *lesson3_defaults
      value: 2
    - name: Lesson4
      completion_criteria: *lesson4_defaults
      value: 2
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      value: 2
  number_of_positive_energy_cores:
    curriculum:
    - name: Lesson0
      completion_criteria: *lesson0_defaults
      value: 1
    - name: Lesson1
      completion_criteria: *lesson1_defaults
      value: 1
    - name: Lesson2
      completion_criteria: *lesson2_defaults
      value: 2
    - name: Lesson3
      completion_criteria: *lesson3_defaults
      value: 2
    - name: Lesson4
      completion_criteria: *lesson4_defaults
      value: 3
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 3
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 4
    - name: Lesson7
      value: 5
  number_of_negative_energy_cores:
    curriculum:
    - name: LessonPushBlock
      completion_criteria: *lessonpushblock_defaults
      value: 0
    - name: LessonPushBlockTwoGoals
      completion_criteria: *lessonpushblock2_defaults
      value: 1
    - name: LessonPushBlockTwoGoalsWithBall
      completion_criteria: *lessonpushblock2ball_defaults
      value: 1
    - name: Lesson0
      completion_criteria: *lesson0_defaults
      value: 1
    - name: Lesson1
      completion_criteria: *lesson1_defaults
      value: 1
    - name: Lesson2
      completion_criteria: *lesson2_defaults
      value: 2
    - name: Lesson3
      completion_criteria: *lesson3_defaults
      value: 2
    - name: Lesson4
      completion_criteria: *lesson4_defaults
      value: 3
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 3
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 4
    - name: Lesson7
      value: 5